version: '3'

volumes:
  squash-tm-db:
  squash-tm-plugins:

services:
  mysql:
    image: amd64/mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: V3ry1ns3cur3P4ssw0rd
      MYSQL_DATABASE: squashtm
      MYSQL_PASSWORD: V3ry1ns3cur3P4ssw0rd
      MYSQL_USER: squashtm
    volumes:
    - squash-tm-db:/var/lib/mysql
  squash-tm:
    build: ./
    image: fjudith/squash-tm:1.19.0-alpine
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_NAME: squashtm
      DB_USERNAME: squashtm
      DB_PASSWORD: V3ry1ns3cur3P4ssw0rd
      #DB_PORT: 5432
    volumes:
    - squash-tm-plugins:/usr/share/squash-tm/plugins
    ports:
    - 32770:8080/tcp
