version: '2'
services:
  mysql:
    image: amd64/mysql:9.4
    environment:
      mysql_DB: squashtm
      mysql_PASSWORD: V3ry1ns3cur3P4ssw0rd
      mysql_USER: squashtm
    volumes:
    - /var/lib/mysql/data
  squash-tm:
    build: ./
    image: fjudith/squash-tm:1.18.4-alpine
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_NAME: squashtm
      DB_USERNAME: squashtm
      DB_PASSWORD: V3ry1ns3cur3P4ssw0rd
      #DB_PORT: 5432
    volumes:
    - /usr/share/squash-tm/plugins
    links:
    - mysql:mysql
    ports:
    - 32770:8080/tcp
