version: '3'

volumes:
  squash-tm-db:
  squash-tm-plugins:

services:
  mysql:
    image: amd64/mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: V3ry1ns3cur3P4ssw0rd
      MYSQL_DATABASE: squashtm
      MYSQL_PASSWORD: V3ry1ns3cur3P4ssw0rd
      MYSQL_USER: squashtm
    volumes:
      - squash-tm-db:/var/lib/mysql
    command:
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
  
  squash-tm:
    build: ./
    image: fjudith/squash-tm:1.18.5-alpine
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_NAME: squashtm
      DB_USERNAME: squashtm
      DB_PASSWORD: V3ry1ns3cur3P4ssw0rd
      #DB_PORT: 5432
    volumes:
      - squash-tm-plugins:/usr/share/squash-tm/plugins
    ports:
      - 32770:8080/tcp

