version: '2'
services:
  postgres:
    image: amd64/postgres:9.4
    environment:
      POSTGRES_DB: squashtm
      POSTGRES_PASSWORD: V3ry1ns3cur3P4ssw0rd
      POSTGRES_USER: squashtm
    volumes:
    - /var/lib/postgresql/data
  squash-tm:
    build: ./
    image: fjudith/squash-tm:1.18.4-alpine
    environment:
      DB_TYPE: postgresql
      DB_HOST: postgres
      DB_NAME: squashtm
      DB_USERNAME: squashtm
      DB_PASSWORD: V3ry1ns3cur3P4ssw0rd
      #DB_PORT: 5432
    volumes:
    - /usr/share/squash-tm/plugins
    links:
    - postgres:postgres
    ports:
    - 32760:8080/tcp
