env:
  global:
  # Docker Repository
  - REPO=fjudith/squash-tm
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - ALPINE_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "alpine"; else echo ${TRAVIS_BRANCH}-alpine ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "vcsuPeIh1niGZN+XPwCbc82kZipNSHYzjiqgcYhlgw5xXEu9mOa9OmieVuswVNiLcRRdRpdgCPF7KAYItI8FE6zIWdqmRRukeSq6iIg9emKl6Y3l6YM5p79XzqIyZLyJ2pVUBu4/fziS8gXKCjvltZok0by9D3eJ5ZmGFkwKdZfpo1qJmdeFlKUkDmisR69OmboU9X636NqjTUIpOdeRuA1wF3+Wzt6Vi26O6DcpAHIddMJZuID/cEsIIrp9oeFRJrlLCRD4W9Wa3izvmZ3te28Sv/NqEFpa8ZeOFCv25PB5r4InRAXF3LWFVkHgBS7Uk1EOkuSgq4+oZTZIZaJimudDp/l2Ec2QhSdBYdCrUt7Qafd2H5uv1qpCf5qBfIbeykAfEU+hnWejGxKff599jTfqvUXMcowhJtwI8q9PmAkPbD3FiBswcxxKZJm5gqeim8DkEMEWNMRM8AEPrjOYmr72ORjekUGeHrvSAi+g3wvEtb0PFbFmkatkNqFEp/wSW8n5UUgxG2GrByBI4d4iEy/pqSm9/pKnHSKfgUeAuNKQN5I2iNqI1LP74wu4ab5pNNcMGLvsIxJKO5YB5Lgv9mbPKcDKIG7TXaUho2uWXmkRiLWnAyvPVV0nxZXQg1lJGonmON6i7Wsf9FzYs9Oo3fBjmXoneHfov04UWygM8Og="
  - secure: "O8TQOc3rIunEaeKFU43dAQufSZIVMqKOnuYc4VwtvlkbetiCwiW0+WzNHOFh1ZHTo4HqwMZMObCoAo757sNetKrxN2JYBGKp23noqjjz21LIZ00MkS1GxHAcNydFe1z/+ZYYUcCypevpFMSGEDjZclsFNcFZyUlIeU5XxsZEk5+kzFziJvFHxeq9jEU0NVukfK/y1keYrv188yBy+rKUshJaSK2lM+P46nIlE5hvM+Ln9JKSeQZ+UEy/xUIYd2Y8+b5hl6cTQeC2bkddn/Nnzxjv52snGNMJQL6MbxI/J7dP5KDjMolp0Tw4R5L/WvDnk1Q417Wuil8snOMkfiaYCujNGz+KKl4AIZUMMaS1EgkKnbISkKnGIUzApqJf7JVV3iFzrcO1rM1vaMuXlpL/56GLG9/Iu2msnYgUb2AM0H8K7Qi5iPX9mbta0s/lMDReMmLBlZhV5M1HEQ8nWBFMrkkKskhKO+8fR/DS87bmIjkSDRxN3IyJ7roTH2mlfLpMgREZDwr4NXPVFWlpMPCsOsmgonb9pjHPOhhfcCxejwqONmHnc2ok99137MUfKN/ad9XtpEKSvcFOp+/lq1IFpaIL/qPfPXV5HdnSjI+dm7zfhPbiOaZihkA/zlaNgsNosyYYrA3FzUbOGJWr1sncrRMseYpHxTIJtxc8O4HHUQs="


sudo: required
services:
  - docker


before_install:
  - pushd ./debian/ && docker-compose -f ./docker-compose.yml -p sqtm1 up --build -d --force-recreate && popd
  - pushd ./alpine/ && docker-compose -f ./docker-compose.yml -p sqtm2 up --build -d --force-recreate && popd
  - SQTM1_CONTAINERID=$(docker ps -qa -f name="sqtm1_squash-tm_1")
  - SQTM2_CONTAINERID=$(docker ps -qa -f name="sqtm2_squash-tm_1")

script:
  # Wait for Waarp-R66 to start
  - sleep 20
  - docker ps -a
  - docker logs ${SQTM1_CONTAINERID} --tail 100
  - docker logs ${SQTM2_CONTAINERID} --tail 100
  # -i, --include – include protocol headers in the output (H/F)
  # -X, --request – specify request  COMMAND (GET, PUT, DELETE…)  to use
  - docker exec ${WAARP1_CONTAINERID} /bin/bash -c "curl -i -L http://localhost:8080/squash-tm"
  - docker exec ${WAARP2_CONTAINERID} /bin/bash -c "curl -i -L http://localhost:8080/squash-tm"



after_success:
  - echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
  - docker tag ${REPO}:${TAG} ${REPO}:travis-${TRAVIS_BUILD_NUMBER}
  - docker tag ${REPO}:${ALPINE_TAG} ${REPO}:travis-${TRAVIS_BUILD_NUMBER}-alpine
  - docker push $REPO