version: '3'

volumes:
  squash-tm-db:
  squash-tm-plugins:

services:
  postgres:
    image: amd64/postgres:9.4
    environment:
      POSTGRES_DB: squashtm
      POSTGRES_PASSWORD: V3ry1ns3cur3P4ssw0rd
      POSTGRES_USER: squashtm
    volumes:
    - squash-tm-db:/var/lib/postgresql/data
  squash-tm:
    build: ./
    image: fjudith/squash-tm:1.18.5
    environment:
      DB_TYPE: postgresql
      DB_HOST: postgres
      DB_NAME: squashtm
      DB_USERNAME: squashtm
      DB_PASSWORD: V3ry1ns3cur3P4ssw0rd
      #DB_PORT: 5432
    volumes:
    - squash-tm-plugins:/usr/share/squash-tm/plugins
    ports:
    - 32760:8080/tcp
